### DISCUSSION TITLE
Custom User Themes

### DISCUSSION THREAD

**Discussion by jothepro** [jothepro/doxygen-awesome-css#13] [Show and tell]
*Doxygen Awesome CSS* is designed to be easily customizable by adjusting CSS variables.

In this place you can share your own customized styles with other users. I am really interested in how you optimize this theme to work best for you!

Examples for adjustments that you might want to share:

- Different Colors scheme for code blocks (fragments). 
- Custom colors for light/dark mode.
- Primary theme colors that look beautiful.
- Colored navigation/title bars that work great in light/dark mode.

To share your style, add a comment to this discussion, with the following information:
- **Title**: Give your style a unique title.
- **Version**: What version of _Doxygen Awesome_ are you using?
- **Screenshot**: A representative Screenshot that highlights the main features of your style.
- **Link** (optional): A link to a public documentation that uses your style.
- **Code**: A code block that contains the variables that you adjusted.

Please do not post content that changes things other than the CSS-variables provided by _Doxygen Awesome_! If you miss a configuration option to achieve what you want to do, or you made adjustments to the CSS to fix a bug, please open an issue or a PR.

**Comment by jothepro** [comment]
# Solarized Light Code Blocks
Created by @r0ckarong 
Version: v1.4.0
<img width="917" src="https://user-images.githubusercontent.com/21294002/115437927-15443c00-a20d-11eb-85f8-2ef84fe9bf1f.png">
```css
  --fragment-background: #fdf6e3;
  --fragment-foreground: #586e75;
  --fragment-keyword: #cb4b16;
  --fragment-keywordtype: #268bd2;
  --fragment-keywordflow: #859900;
  --fragment-token: #2aa198;
  --fragment-comment: #657b83;
  --fragment-link: #d33682;
  --fragment-preprocessor: #2aa198;
  --fragment-linenumber-color: #586e75;
  --fragment-linenumber-background: #eee8d5;
```

**Reply by r0ckarong** [reply]
By the way, I'm just using the default doxygen-awesome.css and add another stylesheet that overrides the variables I need changing in a second stylesheet. 

If you add that as another entry in the doxygen HTML_EXTRA_STYLESHEET line they are both inserted (actually applies to as many stylesheets as you want)!

This way, I can just pull the latest version of this repo and maintain my customizations at the same time. Just make sure to add the supplementary stylesheet _last_ so the values actually override those from doxygen-awesome.css. I find this much easier than having to merge the development progress from this repo into a fully customized file. If something about the main stylesheet changes, I just need to adjust a few things in my supplemental file.

**Comment by gmarull** [comment]
# Zephyr

Version: 1.6.1
Screenshot:

![image](https://user-images.githubusercontent.com/25011557/151257960-ee6dfaca-680c-498f-a07d-ff0279f8f0b9.png)

Link (optional): https://docs.zephyrproject.org/latest/doxygen/html/index.html
Code: https://github.com/zephyrproject-rtos/zephyr/tree/main/doc/_doxygen

**Comment by mwiesenberger** [comment]
## Feltor
Version 1.6.1
Screenshot:
![Screenshot from 2022-02-18 10-28-59](https://user-images.githubusercontent.com/5844863/154655620-60bcb22f-e89d-4092-8f78-a5a4c813da24.png)
Link: https://mwiesenberger.github.io/feltor/dg/html/modules.html


Code  https://github.com/feltor-dev/feltor/tree/master/doc

Like @r0ckarong suggested above I placed my changes in a second stylesheet "menubar.css" which is included in doxygen's `HTML_EXTRA_STYLESHEET`.
For code rendering I changed the `--font-family-monospace` order because my system only had Courier New available, which looked uneasy, so I ranked "monospace" higher and in the end downloaded "Source Code Pro" .
Further, in light-mode I prefer code also in a light color scheme so I added three blocks: Use light code colors in light-mode and the existing dark code-colors in dark-mdoe. Have a look: 
![code-light-mode](https://user-images.githubusercontent.com/5844863/154653874-2b6872a2-b147-48c2-bd34-a233540121fd.png)
![code-dark-mode](https://user-images.githubusercontent.com/5844863/154653879-f7d0287f-dde2-4364-ac70-f8d01e3fe2ee.png)
Finally, you will find the code for the top left menu items in matching colors
![Screenshot from 2022-02-18 10-38-52](https://user-images.githubusercontent.com/5844863/154657106-d2803d1d-8f06-4d6f-a56e-0880ecd56909.png)

**Comment by sdegrande** [comment]
Version 2.0.3, a small custom.css, to mark Namespaces in the Class list

![Mark_Namespaces](https://user-images.githubusercontent.com/1544860/169538415-b671ab7a-f066-46c9-a71a-33f09af6913c.png)

```
div#nav-tree ul.children_ul ul.children_ul ul.children_ul a[class^="namespace"]::before {
  content: "N ";
  /* from .icon */
  font-family: Arial, Helvetica;
  font-weight: bold;
  font-size: 12px;
  height: 14px;
  width: 16px;
  display: inline-block;
  background-color: #0081FA;
  color: white;
  text-align: center;
  border-radius: 4px;
  margin-left: 2px;
  margin-right: 6px;
}
```

**Reply by leissa** [reply]
Nice. Would like to see this upstream :+1:

**Comment by leissa** [comment]
![thorin_theme](https://user-images.githubusercontent.com/8067180/187539316-e68fbee9-588c-4de2-bf04-196243591cd8.jpg)
Pretty much the vanilla theme but a couple of magic from the Doxygen site that works perfectly with this theme:

* Version: 2.0.3
* Link: https://anydsl.github.io/thorin2/

**Comment by briederer** [comment]
# GitLab Corner with animation

Inspired by the GitHub-Corner used in this repo I've searched the web for some input (see credits at the end) and created a similar thing for the Gitlab-Logo.

## custom.css
 ```css
/* Gitlab-Corner from https://bryce.io/gitlab-corners/ */
.gitlab-corner-wrapper{
    overflow:hidden;
    width:var(--gitlab-margin);
    height:var(--gitlab-margin);
    position:absolute;
    top:0;
    right:0
}

.gitlab-corner{
    position:absolute;
    top:-11px;
    right:-46px;
    transform:rotate(45deg);
    background:var(--gitlab-corner-color);
    border:40px solid var(--gitlab-corner-color);
    border-bottom:none;
    border-top:var(--gitlab-corner-color) solid 14px;
    z-index: 10000; /*higher than main-menu which has 9999*/
}

.gitlab-corner svg{
    width:calc(0.6 * var(--gitlab-margin));
    height:calc(0.6 * var(--gitlab-margin));
    margin-bottom:-4px
}

.cls-1 { fill:#e24329; }
.cls-2 { fill:#fc6d26; }
.cls-3 { fill:#fca326; }

.gitlab-corner:hover .cls-1 {
    animation: cycle 600ms;
}

.gitlab-corner:hover .cls-2 {
    animation: cycleMid 600ms;
}

.gitlab-corner:hover .cls-3 {
    animation: cycleEnd 600ms;
}

@keyframes cycle {
    from { fill:#fc6d26; }
    20%  { fill:#fca326; }
    40%  { fill:#e24329; }
    60%  { fill:#fc6d26; }
    80%  { fill:#fca326; }
    to   { fill:#e24329; }
}

@keyframes cycleMid {
    from { fill:#e24329; }
    20%  { fill:#fc6d26; }
    40%  { fill:#fca326; }
    60%  { fill:#e24329; }
    80%  { fill:#fc6d26; }
    to   { fill:#fca326; }
}

@keyframes cycleEnd {
    from { fill:#fca326; }
    20%  { fill:#e24329; }
    40%  { fill:#fc6d26; }
    60%  { fill:#fca326; }
    80%  { fill:#e24329; }
    to   { fill:#fc6d26; }
}

@media (max-width:500px){
    .gitlab-corner:hover .cls-1,
    .gitlab-corner:hover .cls-2,
    .gitlab-corner:hover .cls-3 {animation:none}

    .gitlab-corner .cls-1 {animation:cycle .6s}
    .gitlab-corner .cls-2 {animation:cycleMid .6s}
    .gitlab-corner .cls-3 {animation:cycleEnd .6s}
}
```

## header.html

Should be directly added after `<body>` is opened.

```html
<!-- Gitlab-Corner from https://bryce.io/gitlab-corners/ -->
   <div class="gitlab-corner-wrapper">
      <a href="https://gitlab.com/your_group/your_project" target="_blank" class="gitlab-corner" aria-label="View source on GitLab">
         <!-- Old Gitlab-logo -->
         <!-- <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 586 559">
            <path id="path46" class="cls-1" d="M461.17,301.83l-18.91-58.12L404.84,128.43a6.47,6.47,0,0,0-12.27,0L355.15,243.64H230.82L193.4,128.43a6.46,6.46,0,0,0-12.26,0L143.78,243.64l-18.91,58.19a12.88,12.88,0,0,0,4.66,14.39L293,435,456.44,316.22a12.9,12.9,0,0,0,4.73-14.39"></path>
            <path id="path50" class="cls-2" d="M293,434.91h0l62.16-191.28H230.87L293,434.91Z"></path>
            <path id="path58" class="cls-1" d="M293,434.91,230.82,243.63h-87L293,434.91Z"></path>
            <path id="path66" class="cls-3" d="M143.75,243.69h0l-18.91,58.12a12.88,12.88,0,0,0,4.66,14.39L293,435,143.75,243.69Z"></path>
            <path id="path74" class="cls-2" d="M143.78,243.69h87.11L193.4,128.49a6.47,6.47,0,0,0-12.27,0l-37.35,115.2Z"></path>
            <path id="path78" class="cls-1" d="M293,434.91l62.16-191.28H442.3L293,434.91Z"></path>
            <path id="path82" class="cls-3" d="M442.24,243.69h0l18.91,58.12a12.85,12.85,0,0,1-4.66,14.39L293,434.91l149.2-191.22Z"></path>
            <path id="path86" class="cls-2" d="M442.28,243.69h-87.1l37.42-115.2a6.46,6.46,0,0,1,12.26,0l37.42,115.2Z"></path>
         </svg> -->
        <!-- New Gitlab-logo -->
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 380 380">
            <path class="cls-1" d="M282.83,170.73l-.27-.69-26.14-68.22a6.81,6.81,0,0,0-2.69-3.24,7,7,0,0,0-8,.43,7,7,0,0,0-2.32,3.52l-17.65,54H154.29l-17.65-54A6.86,6.86,0,0,0,134.32,99a7,7,0,0,0-8-.43,6.87,6.87,0,0,0-2.69,3.24L97.44,170l-.26.69a48.54,48.54,0,0,0,16.1,56.1l.09.07.24.17,39.82,29.82,19.7,14.91,12,9.06a8.07,8.07,0,0,0,9.76,0l12-9.06,19.7-14.91,40.06-30,.1-.08A48.56,48.56,0,0,0,282.83,170.73Z" />
            <path class="cls-2" d="M282.83,170.73l-.27-.69a88.3,88.3,0,0,0-35.15,15.8L190,229.25c19.55,14.79,36.57,27.64,36.57,27.64l40.06-30,.1-.08A48.56,48.56,0,0,0,282.83,170.73Z" />
            <path class="cls-3" d="M153.43,256.89l19.7,14.91,12,9.06a8.07,8.07,0,0,0,9.76,0l12-9.06,19.7-14.91S209.55,244,190,229.25C170.45,244,153.43,256.89,153.43,256.89Z" />
            <path class="cls-2" d="M132.58,185.84A88.19,88.19,0,0,0,97.44,170l-.26.69a48.54,48.54,0,0,0,16.1,56.1l.09.07.24.17,39.82,29.82s17-12.85,36.57-27.64Z" />
        </svg>
      </a>
   </div>
```
## Result
### New logo
![New logo](https://user-images.githubusercontent.com/20151553/192734422-438b0746-0350-4d05-b437-ca52c6dd13e2.png)

### Old logo
![Old logo](https://user-images.githubusercontent.com/20151553/192736103-94a57c29-547d-4ec4-93d9-659c6f1d7b6d.png)

## Credits
Special thanks go to the webpage [https://bryce.io/gitlab-corners/](https://bryce.io/gitlab-corners/) which already did the hardest job for the animation of the old logo. Also there different colour-variants can be found.
The new logo svg-path has been taken from the official [GitLab Press kit](https://about.gitlab.com/press/press-kit/), see [.svg-file](https://about.gitlab.com/images/press/logo/svg/gitlab-logo-500.svg)

**Comment by briederer** [comment]
# Version switcher

I was intrigued by the version switcher that the [ROOT-documentation](https://root.cern/doc/master/) uses and incorporated it into my project. The original implementation is done by @Axel-Naumann and is released under the git repo [root-project/doxyvers](https://github.com/root-project/doxyvers) licensed under [LGPL-3.0 license](https://github.com/root-project/doxyvers/blob/master/LICENSE).

![Dropdown switcher](https://user-images.githubusercontent.com/20151553/192739736-8b5a9746-6ce7-4b27-b7cd-428f9d9613bc.png)
![Expanded menu](https://user-images.githubusercontent.com/20151553/192739855-616e9ac8-6019-41ef-a577-3ee38ecd7eb9.png)

Since a few things need to be considered when integrating it using doxygen-awesome I'll post here the necessary modifications.

## dropdown.css
```css
/* (c) Axel Naumann, CERN; 2020-03-02 */
/* Modified by Bernd Riederer to incorporate color schemes from doxygen-awesome */
/* Adapted from https://www.w3schools.com/howto/howto_css_dropdown.asp */
.dropbtn {
  margin-left: var(--spacing-small);
  border: 1px solid lightgray;
  color: white;
  background-color: var(--primary-color);
  padding:  var(--spacing-small);
  font-size: 14px;
  min-width: 85px;
}
.dropbtn:after{
    content: '';
    border: 4px solid transparent;
    border-top: 4px solid white;
    margin-left: 12px;
    margin-bottom: 3px;
    display: inline-block;
    vertical-align: bottom;
}

/* The container <div> - needed to position the dropdown content */
.dropdown {
  position: relative;
  display: inline-block;
}

/* Dropdown Content (Hidden by Default) */
.dropdown-content {
  display: none;
  position: absolute;
  margin-left: var(--spacing-small);
  background-color: var(--primary-lightest-color);
  min-width: 75px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 1;
}

/* Links inside the dropdown */.dropdown-content a {
  color: black;
  padding: 4px 16px;
  text-decoration: none;
  display: block;
}

/* Change color of dropdown links on hover */
.dropdown-content a:hover {background-color: var(--primary-lighter-color);}

/* Show the dropdown menu on hover */
.dropdown:hover .dropdown-content {display: block;}

/* Change the background color of the dropdown button when the dropdown content is shown */
.dropdown:hover .dropbtn {
   color: black;
   background-color:  var(--primary-light-color);
}
```

## selectversion.js

This part may need some modification depending on the URL and the repo-layout that is used. Nevertheless for me the following works.

```js
/// Modified version of ROOT-version selector
/// Modified by Bernd Riederer
/// (c) Axel Naumann, CERN; 2020-03-02

/// Configurable section.

// What the master is called. Leave untouched if master has no doc.
let master = 'master';

/// Pathname part of the URL containing the different versioned doxygen
/// subdirectories. Must be browsable.
let urlroot = '/project-name/docs-subfolder';

///=============================================================================
// Remove trailing '/'.
if (urlroot[urlroot.length - 1] == '/')
  urlroot = urlroot.substring(0, urlroot.length - 1)
let urlrootdirs = urlroot.split('/').length;

function url2version(patharr) {
  // Given the directory array of a URL (i.e. without domain), extract the
  // version corresponding to the URL.
  // E.g. for `https://example.com/doc/master/classX.html`, the directory array
  // becomes `["doc", "master, "classX.html"]. This function might return
  // the second element, `master`.
  return patharr[urlrootdirs];
}

let patharr = window.location.pathname.replace(/\/+/g, '/').split('/');
let thisvers = url2version(patharr);
$('.dropbtn').html(thisvers);

// https://stackoverflow.com/questions/30622369
$.get(urlroot + '/', (data) => {
  let ret = parseDirectoryListing(data);
  $('.dropdown-content').append(ret.join(''));

  // Now check which links actually exist, and remove the href for those
  // that don't.
  $('.dropdown-content')
    .find('.verslink')
    .each(function () {
      var el = $(this);
      var request = new XMLHttpRequest();
      request.open('HEAD', el.attr('href'), true);
      request.onreadystatechange = function () {
        if (request.readyState === 4) {
          if (request.status === 404) {
            el.removeAttr('href');
            el.css({
              'color': "gray",
              'text-decoration': 'line-through'
            });
          }
        }
      };
      request.send();
    });
});

function parseDirectoryListing(text) {
  let docs = text.match(/href="([^/][^"]+)"/g); // only directories.
  docs = docs.map((x) =>
    x.replace(/.\//g, '')
      .replace(/href="/, '')
      .replace(/"$/, ''))
    .sort().reverse();
  docs = docs.filter(function (line) {
    // suppress link to current version
    return !RegExp(thisvers).test(line)
      // suppress hidden dirs
      && !/^[.]/.test(line);
  });

  if (docs.includes(master)) {
    // Move "master" first.
    docs.splice(docs.findIndex(el => el == master), 1);
    docs.splice(0, 0, master);
  }
  docs = docs.map((x) => '<a class="verslink" href="'
    + patharr.slice(0, urlrootdirs).join('/')
    + '/' + x + '/' + patharr[patharr.length - 1] + '">'
    + x
    + '</a>');
  return docs;
}
```

## header.html
Replacing the projectnumber of doxygen by the dropdown. Note the path has changed compared to [root-project/doxyvers](https://github.com/root-project/doxyvers).

```html
<!--BEGIN PROJECT_NUMBER-->
<!-- BEGIN version select -->
<div class="dropdown" id="projectnumber">
   <button class="dropbtn">$projectnumber</button>
   <div class="dropdown-content">
   </div>
</div>
<script type="text/javascript" src="$relpath^selectversion.js"></script>
<!-- END version select -->
<!--<span id="projectnumber">$projectnumber</span>--><!--END PROJECT_NUMBER-->
```

**Comment by ilg-ul** [comment]
# Cards

I did an experimental implementation of _cards_ in the home page of one of my projects, and I think that it might be a good starting point for a new feature to be added to this theme:

![Screenshot 2023-05-19 at 21 01 18](https://github.com/jothepro/doxygen-awesome-css/assets/362732/5455e3b6-7fa1-4c90-947d-d6b1358e81d9) 

The initial post was <https://github.com/jothepro/doxygen-awesome-css/discussions/117>.

The html & css code can be seen in <https://github.com/micro-os-plus/utils-lists-xpack/tree/xpack-develop/website>.

As a possible improvement, I was thinking on adding some small images on top of the card title, but currently I don't have these images, I have to further search for something suitable.
 
If someone with a better knowledge of CSS is interested in such a feature and is willing to further improve it, I'd be more than happy to test the result.

**Reply by ilg-ul** [reply]
I added some small SVG images to the cards, I think this looks even nicer:

![With images](https://user-images.githubusercontent.com/362732/241309654-b9cf1728-6c6f-4660-b291-74fcee4f700a.png)

**Reply by sdegrande** [reply]
Very nice ! I'm quite sure that I'll use it ! Thx.

**Reply by ilg-ul** [reply]
The current CSSs are in:

- <https://github.com/micro-os-plus/build-helper-xpack/blob/xpack/doxygen/cards.css>

and the HTML in:

- <https://github.com/micro-os-plus/utils-lists-xpack/blob/xpack-develop/website/pages/home.md?plain=1>

If you have suggestions to improve the implementation, please let me know.

**Reply by ilg-ul** [reply]
Here is another site using such cards in the home page:

![Screenshot 2023-05-30 at 12 53 46](https://github.com/jothepro/doxygen-awesome-css/assets/362732/fb195430-c027-4cdd-8549-16bbdcce6b6b)

**Reply by sdegrande** [reply]
I just tried it, and it is not very visible in dark mode. Do you know what shadow color should be used in dark mode ?

**Reply by jpgarza93** [reply]
You guys could use ALIASES for this, its what i do:

![image](https://github.com/user-attachments/assets/323b8652-474c-47a4-bb5e-416f91fc9967)
![image](https://github.com/user-attachments/assets/fad3bf32-b6ab-4ba8-a7f9-74d517a8a683)

**ALIASES**
```
ALIASES += card-text{1}="@htmlonly<div class='card-text'>@endhtmlonly\1@htmlonly</div>@endhtmlonly"
ALIASES += col3{3||}="@htmlonly<div class='row'>^^<div class='column'>@endhtmlonly\1@htmlonly</div>^^<div class='column'>@endhtmlonly\2@htmlonly</div>^^<div class='column'>@endhtmlonly\3@htmlonly</div>^^</div>@endhtmlonly"
```

*CSS*
```css
.card {
  background: var(--code-background);
  border-radius: var(--border-radius-small);
  flex: 1;
  margin: 0;
}
.card .card-text {
  padding-top: 7.5px;
}
.card .card-text, .card-text > p, .card-text a {
  font-size: var(--navigation-font-size) !important;
}
.card-text div > a {
  display: contents;
  line-height: var(--content-line-height);
}
.card .card-text, .card-text > p:last-child {
  margin-bottom: 0px;
}

@media only screen and (max-width: 767px) {
  .row {
    flex-direction: column !important;
  }
}
.row {
  display: flex;
  gap: 25px;
  align-items: stretch;
}
.column {
  display: flex;
  flex: 50%;
  box-sizing: border-box;
}
```

**Comment by vs9h** [comment]
# Dracula theme
Version: 2.2.1
Screenshots:
![screenshot-20230819-221032Z-all](https://github.com/jothepro/doxygen-awesome-css/assets/56894551/31410a72-619a-4807-8c15-067c51379be6)
![screenshot-20230819-221037Z-all](https://github.com/jothepro/doxygen-awesome-css/assets/56894551/d0f16d32-755f-4239-acf5-f34b7353bd3b)

## Description

Discover my take on the Dracula-inspired Doxygen theme, featuring a dark mode true to the original, and a personal twist in the form of a purple-themed light mode. 

I've also incorporated new icons for dark/light modes. The CSS settings have been fine-tuned, drawing from [custom.css](https://github.com/jothepro/doxygen-awesome-css/blob/main/doxygen-custom/custom.css) and updates to [doxygen-awesome.css](https://github.com/jothepro/doxygen-awesome-css/blob/main/doxygen-awesome.css). 

Note that these are my adaptations and may vary from the original Dracula theme.

## Changes

### doxygen-awesome.css
```css
html {
    /* primary theme color. This will affect the entire websites color scheme: links, arrows, labels, ... */
    --primary-color: #bd93f9;
    --primary-dark-color: #9270e4;
    --primary-light-color: #9270e4;

    /* page base colors */
    --page-background-color: #ffffff;
    --page-foreground-color: #2f4153;
    --page-secondary-foreground-color: #6f7e8e;

    /* color for all separators on the website: hr, borders, ... */
    --separator-color: #bd93f965;

    /* border radius for all rounded components. Will affect many components, like dropdowns, memitems, codeblocks, ... */
    --border-radius-large: 22px;
    --border-radius-small: 9px;
    --border-radius-medium: 14px;

    /* default spacings. Most components reference these values for spacing, to provide uniform spacing on the page. */
    --spacing-small: 8px;
    --spacing-medium: 14px;
    --spacing-large: 19px;

    --top-height: 125px;

    ...
}

html.dark-mode {
    color-scheme: dark;

    --primary-color: #bd93f9;
    --primary-dark-color: #9270e4;
    --primary-light-color: #9270e4;
    --primary-lighter-color: #191e21;
    --primary-lightest-color: #191a1c;

    --page-background-color: #21222c;
    --page-foreground-color: #d2dbde;
    --page-secondary-foreground-color: #859399;
    --separator-color: #3a3246;
    --side-nav-background: #282a36;
    --side-nav-foreground: #f8f8f2;
    --toc-background: #282A36;
    --searchbar-background: var(--page-background-color);

    ...
}

```

## doxygen-awesome-darkmode-toggle.js
```js
class DoxygenAwesomeDarkModeToggle extends HTMLElement {
    // SVG icons from https://www.iconfinder.com/
    // Link to the author https://www.iconfinder.com/rasmusnielsendk
    static lightModeIcon = `<svg height="20.315mm" viewBox="0 0 57.587 57.587" width="20.315mm" xmlns="http://www.w3.org/2000/svg"><title/><circle cx="28.398" cy="28.696" fill="#f5ce42" r="16.948"/></svg>`
    static darkModeIcon = `<svg height="20.315mm" viewBox="0 0 57.587 57.587" width="20.315mm" xmlns="http://www.w3.org/2000/svg"><title/><path d="M41.446,32.535A16.647,16.647,0,0,1,25.163,12.361a16.655,16.655,0,1,0,20.1,19.717A16.7,16.7,0,0,1,41.446,32.535Z" fill="#7269af"/></svg>`
    ...
}
```

**Comment by GregoryKogan** [comment]
# Tokyo Night Storm

## Screenshot

<img width="1492" alt="image" src="https://github.com/jothepro/doxygen-awesome-css/assets/60318411/c61cde7f-9c22-489d-94d9-614adb675489">

## Live example

https://gregorykogan.github.io/result-cpp/

## custom.css

```css
html.dark-mode {
  --primary-color: #7aa2f7;
  --primary-dark-color: #bb9af7;
  --primary-light-color: #b4f9f8;

  --page-background-color: #24283b;
  --page-foreground-color: #a9b1d6;
  --page-secondary-foreground-color: #9aa5ce;
  --separator-color: #565f89;
  --side-nav-background: #1a1b26;

  --code-background: #31364e;
  --code-foreground: #73daca;

  --tablehead-background: #1a1b26;

  --blockquote-background: #414868;
  --blockquote-foreground: #73daca;

  --warning-color: #e0af68;
  --warning-color-dark: #ff9e64;
  --warning-color-darker: #f7768e;
  --bug-color: #f7768e;

  --fragment-background: #24283b;
  --fragment-foreground: #a9b1d6;
  --fragment-keyword: #bb9af7;
  --fragment-keywordtype: #a9b1d6;
  --fragment-keywordflow: #bb9af7;
  --fragment-token: #9ece6a;
  --fragment-comment: #565f89;
  --fragment-link: #73daca;
  --fragment-preprocessor: #bb9af7;
  --fragment-linenumber-color: #414868;
  --fragment-linenumber-background: #24283b;
  --fragment-linenumber-border: #1a1b26;
}
```

## Source

Color palette taken from [vscode tokyo night theme](https://github.com/enkia/tokyo-night-vscode-theme)

**Comment by jpgarza93** [comment]
# Minimal Tabs

![image](https://github.com/user-attachments/assets/51df85e0-b120-42f0-b0ad-25515bc3f662)

## CSS

```css
/** TABS **/

/* button wrapper */
.tabs-overview {
  border-bottom: 0px !important;
  font-weight: 500 !important;
}

/* button */
.tab-button {
  padding: 0 !important;
}

/* button content */
.tab-title {
  box-shadow: none !important;
  border-radius: var(--border-radius-small) !important;
  color: var(--deprecated-color-darker); /*or --page-secondary-foreground-color*/
}

/* button content (not-active) (hover) */
.tab-button:hover:not(.active) .tab-title {
  border-radius: var(--border-radius-small) !important;
  color: inherit !important;
}

/* button content (active) */
.tab-button.active .tab-title {
  box-shadow: none !important;
  color: var(--primary-color) !important;
  font-weight: 600;
  background: var(--page-background-color) !important;
  border-radius: var(--border-radius-small) var(--border-radius-small) 0 0 !important;
  border: 1px solid var(--separator-color) !important;
  border-bottom: 1px solid transparent !important;
}

/* button content underline */
.tab-button.active::after {
  display: none !important;
}

/* content */
.tabbed > ul {
  border: 1px solid var(--separator-color);
  padding: 0 13px !important;
  margin-top: -1px !important;
}
```

## ALIASES
```
# tabs
ALIASES += tab{2|}="@htmlonly<li><span class='tab-title'>@endhtmlonly^^\1^^@htmlonly</span>@endhtmlonly^^\2^^@htmlonly</li>@endhtmlonly"
ALIASES += tab2{2||}="@tab{ \1 | \2 }"
ALIASES += tabs{1}="@htmlonly<div class='tabbed'><ul>@endhtmlonly^^\1^^@htmlonly</ul></div>@endhtmlonly"
```

## MARKDOWN USAGE

```
@tabs{
@tab{Title1|Content1}
@tab{Title2|Content2}
...
}
```
