### DISCUSSION TITLE
Call Graphs not fitting

### DISCUSSION THREAD

**Discussion by Frozen71** [jothepro/doxygen-awesome-css#57] [Q&A]
My function call tree is too big and caller graphs not fitting. Is there a way to add a scroll bar or change its size dynamically?

**Comment by jothepro** [comment]
No, this is currently not possible. I assume that you generate graphics with `DOT_IMAGE_FORMAT = svg`? Thanks for pointing this out, I didn't realize that this was a problem!

Pls let me know if adding the following CSS to the end of the `doxygen-awesome.css` stylesheet does resolve your issue. All graphics should now have a scrollbar if they are too wide:

```css
.contents img, .contents .center, .contents center {
    max-width: 100%;
    overflow: scroll;
}
```
