### DISCUSSION TITLE
Curious why this style design was chosen

### DISCUSSION THREAD

**Discussion by jpgarza93** [jothepro/doxygen-awesome-css#71] [Q&A]
It looks like brief summaries show outside the function:
![image](https://user-images.githubusercontent.com/79015116/162285983-d6672d76-5851-4959-8e37-31ca50bb5f57.png)

as suppose to before, when the summary was part of the same group box:
![image](https://user-images.githubusercontent.com/79015116/162286257-34d76b6d-4405-4b69-86ba-8ea1fd8f5c18.png)

now my docs look like this:
![image](https://user-images.githubusercontent.com/79015116/162286493-1741d071-cd2c-45ab-9e00-a669fff2dd40.png)

IMO, seems like grouping them would be a better user experience. Now they seem to be different items. I think it would be better to group them and keep the brief summary in a lighter font/opacity as the older version.

Best!

**Comment by jothepro** [comment]
Sure, that's a reasonable question! 

My intention wasn't to separate the function interface from the summary, but to make a distinction between "code" and "text" content. The new background and font of the function interface is the same as for code listings in the rest of the documentation.
Apart from that I tried to reduce the density of the previous table layout with larger paddings to make the page layout look "cleaner". 

The cost for the changes is a looser visual coupling and the fact that paddings make the overview list a lot longer.

If I could move the summary back into the new "code block" background, I would face 2 problems: 
1. The increased paddings between the blocks will look silly, bc. there is nothing between the "code blocks" but some small empty space.
2. The only distinction between code and text will be the font (monospace vs. sans serif) and maybe the color, like in the default Doxygen theme.

This may be self-fabricated issues to begin with, the original Doxygen layout wasn't bad after all, it just didn't quite match the rest of the doxygen-awesome-css visual appearance. 
Feel free to provide other ideas on how to improve the visual grouping between the function interface and its summary, maybe brainstorming a bit brings up some other interesting solutions! Your proposal to go back to sth similar to the old layout would one viable solution, I guess.
Personally atm I still prefer the appearance of the new layout, although it admittedly comes with some amount of "form over function"-syndrome. 😉

**Reply by jpgarza93** [reply]
Thank you for putting the time to reply back and for all the effort you have invested into this repo. 

I will play around a bit to see if the old layout can be styled like the rest of the doxygen-awesome-css visual appearance

**Reply by jpgarza93** [reply]
What do you think about this? I changed the CSS on the old version:

![image](https://user-images.githubusercontent.com/79015116/163227382-abfd96ad-518d-47b3-b8eb-1f601236b2cf.png)

```css
// Row Cell Padding
td.memItemLeft,
td.memItemRight,
td.mdescLeft,
td.mdescRight {
    padding: 5px;
}

// Row Top-Left Cell
td.memItemLeft {
    border-radius: 5px 0 0 5px;
    border-top: 1px solid var(--separator-color);
    border-left: 1px solid var(--separator-color);
    border-bottom: 1px solid var(--separator-color);
}

// Row Top-Right Cell
td.memItemRight {
    border-radius: 0 5px 5px 0;
    border-top: 1px solid var(--separator-color);
    border-bottom: 1px solid var(--separator-color);
    border-right: 1px solid var(--separator-color);
}

// Row Bottom-Left Cell
td.mdescLeft {
    border-radius: 0 0 0 5px;
    border-left: 1px solid var(--separator-color);
    border-bottom: 1px solid var(--separator-color);
}

// Row Bottom-Right Cell
td.mdescRight {
    border-radius: 0 0 5px 0;
    border-right: 1px solid var(--separator-color);
    border-bottom: 1px solid var(--separator-color);
}

// Separator Row Cell
td.memSeparator {
    border-bottom: 5px solid transparent;
}

// Class Summary/Brief Row 
tr[class*="memdesc"] {
    transform: translateY(-4px) !important;
}

// Selects Separator Row Cell if there is no class summary/brief
tr[class*="memitem"]+tr[class*="separator"]>td.memSeparator {
    border-bottom: 9px solid transparent !important;
}
```

You can select whatever colors and spacing you like, but I think the grouping makes for a better visual experience. Can't wait to hear what you think :)

Thanks!

**Reply by kuenzign** [reply]
I like that in the current version the code is in a monospace font, but I think that the border around only the code lines is a bit jarring in that specific context (it's fine elsewhere).  Perhaps a combination of what you just suggested with monospace font (only for the code parts) would be a good compromise?

**Reply by jpgarza93** [reply]
I think you are suggesting something like this?

![image](https://user-images.githubusercontent.com/79015116/163240556-872e98f7-e6ff-49fc-95da-b0f8a547c06d.png)

```css
// Row Cell Padding
td.memItemLeft,
td.memItemRight,
td.mdescLeft,
td.mdescRight {
    padding: 5px;
}

// Row Top-Left Cell
td.memItemLeft {
    border-radius: 5px 0 0 5px;
    border-top: 1px solid var(--separator-color);
    border-left: 1px solid var(--separator-color);
    border-bottom: 1px solid var(--separator-color);
}

// Row Top-Right Cell
td.memItemRight {
    border-radius: 0 5px 5px 0;
    border-top: 1px solid var(--separator-color);
    border-bottom: 1px solid var(--separator-color);
    border-right: 1px solid var(--separator-color);
}

// Row Bottom-Left Cell
td.mdescLeft {
    border-radius: 0 0 0 5px;
    border-left: 1px solid var(--separator-color);
    border-bottom: 1px solid var(--separator-color);
}

// Row Bottom-Right Cell
td.mdescRight {
    border-radius: 0 0 5px 0;
    border-right: 1px solid var(--separator-color);
    border-bottom: 1px solid var(--separator-color);
}

// Separator Row Cell
td.memSeparator {
    border-bottom: 0px solid transparent;
}

// Code Row 
tr[class*="memitem"] {
    font-family: var(--font-family-monospace);
}

// Class Summary/Brief Row 
tr[class*="memdesc"] {
    transform: translateY(-4px) !important;
}

// Selects Separator Row Cell if there is no class summary/brief
tr[class*="memitem"]+tr[class*="separator"]>td.memSeparator {
    border-bottom: 4px solid transparent !important;
}
```
