### ISSUE TITLE
Function parameters hard to read in dark mode (Doxygen 1.10)

### ISSUE THREAD

**Issue by marktsuchida** [jothepro/doxygen-awesome-css#139]
With Doxygen 1.10 and in dark mode, function parameters are dark red/brown and hard to read:
![image](https://github.com/jothepro/doxygen-awesome-css/assets/660808/d8b6b9b8-c439-44bf-98f2-0e0504c373a8)

I think `doxygen.css` added a `.paramname em` rule that is now winning over the color in `doxygen-awesome.css`'s `.paramname` rule.

I'm currently working around this with the following custom css:
```css
/* Make '.paramname em' identical to '.paramname'. */
.paramname em {
    font-weight: 600;
    color: var(--primary-dark-color);
}
```
