### ISSUE TITLE
C++ template signature has border between template and rest of signature

### ISSUE THREAD

**Issue by sean-parent** [jothepro/doxygen-awesome-css#186]
![Image](https://github.com/user-attachments/assets/f267a8a3-b12c-451a-9aeb-ad6cdcc092fc)

Should appear like this:

![Image](https://github.com/user-attachments/assets/39c1e8ed-aeb9-401a-868d-2794c43b5138)

The following custom CSS is a workaround:

```css

table.memberdecls .memItemLeft,
table.memberdecls .memItemRight,
table.memberdecls .memTemplItemLeft,
table.memberdecls .memTemplItemRight,
table.memberdecls .memTemplParams {
    padding-top: unset;
    border-top: unset;
}

table.memberdecls .memTemplParams {
    border-bottom: 0;
    padding-bottom: 0;
}

```
