### ISSUE TITLE
Markdown code spans no longer render as `<code>` blocks starting with Doxygen v1.14.0

### ISSUE THREAD

**Issue by parmi93** [jothepro/doxygen-awesome-css#187]
Starting with Doxygen v1.14.0 there has been a change regarding markdown code spans

```c
/**
 * My piece of code: `printf("hello");`
 */
```

Starting with Doxygen v1.14.0 the output became:
```html
<span class="tt">printf("hello");</span>
```
which is rendered as:
<img width="584" alt="Image" src="https://github.com/user-attachments/assets/7562bc74-dfe4-45a9-bebe-ce13e86684ae" />

with previous versions of Doxygen the output was:
```html
<code>printf("hello");</code>
```
which was rendered as:
<img width="538" alt="Image" src="https://github.com/user-attachments/assets/41f4a631-68fe-4ca2-a544-36a9d0f5d736" />

Temporarily waiting for an official fix I fixed the problem by adding the following custom.css:
```css
code, .tt {
	white-space: nowrap;
}

.tt, .tt a {
	font-family: var(--font-family-monospace);
	font-size: var(--code-font-size) !important;
}

.tt {
	display: inline;
	background: var(--code-background);
	color: var(--code-foreground);
	padding: 2px 6px;
}

.tt {
	border-radius: var(--border-radius-small);
	border: 1px solid var(--separator-color);
	overflow: hidden;
}
```
