### ISSUE TITLE
Dark theme for SVG graphs

### ISSUE THREAD

**Issue by kuenzign** [jothepro/doxygen-awesome-css#28]
When using raster images (such as the default PNG), doxygen-awesome does a `hue-rotate(180deg) invert()` for `img` tags in dark theme.  When you have `DOT_IMAGE_FORMAT` set to `svg`, Doxygen uses `iframe` tags instead of `img` tags.  Please add `iframe:not([id])` to the css rule for `img` tags, so that the `iframe`s for SVG are also changed for dark theme.

Something like this should probably suffice:
```css
@media (prefers-color-scheme: dark) {
    html:not(.light-mode) div.contents div.dyncontent img,
    html:not(.light-mode) div.contents div.dyncontent iframe:not([id]) {
        filter: hue-rotate(180deg) invert();
    }
}

html.dark-mode div.contents div.dyncontent img,
html.dark-mode div.contents div.dyncontent iframe:not([id]) {
    filter: hue-rotate(180deg) invert();
}
```
