### ISSUE TITLE
Light theme Search Results not working when system theme is Dark

### ISSUE THREAD

**Issue by kuenzign** [jothepro/doxygen-awesome-css#31]
If you have your system theme to Dark, but have the new theme toggle set to Light, the search results stay inverted (dark).  I believe that a `html:not(.light-mode)` is missing here:

https://github.com/jothepro/doxygen-awesome-css/blob/8739758d46602cf90e95e349731faa2ea7109d8d/doxygen-awesome.css#L580-L584

It should probably be this instead:
```css
@media (prefers-color-scheme: dark) {
    html:not(.light-mode) iframe#MSearchResults {
        filter: invert() hue-rotate(180deg);
    }
}
```
