### ISSUE TITLE
icon in darkmode not available

### ISSUE THREAD

**Issue by Marco-Israel** [jothepro/doxygen-awesome-css#43]
In Darkmode the left icon is missing to toggle the mode. In light mode a sun is visible.

Here is the setup:

# Include the required Javascript
HTML_EXTRA_FILES       = doxygen-awesome-css/doxygen-awesome-darkmode-toggle.js

# Add the additional CSS. This is ONLY required for the sidebar-only theme variant!
HTML_EXTRA_STYLESHEET  = doxygen-awesome-css/doxygen-awesome.css \ 
                         doxygen-awesome-css/doxygen-awesome-sidebar-only.css \
                         doxygen-awesome-css/doxygen-awesome-sidebar-only-darkmode-toggle.css

# set custom header & footer files generated in previous step
HTML_HEADER            = header.html
HTML_FOOTER            = footer.html

**Comment by jothepro** [comment]
What browser and operating system are you using? Can you provide a screenshot?

The icon in the button by default is just using the emojis '☀️' and '🌛'. This means that the appearance can differ across different systems. My guess is that your system or browser does not (fully) support emojis? 🤔 

My suggestions on how to fix the problem for you:
- You could overwrite the `--darkmode-toggle-button-icon` CSS property [here](https://github.com/jothepro/doxygen-awesome-css/blob/main/doxygen-awesome.css#L210) and [here](https://github.com/jothepro/doxygen-awesome-css/blob/main/doxygen-awesome.css#L256) with a symbol that works for you. 
- The toggle button is an empty html node that is styled using CSS [here](https://github.com/jothepro/doxygen-awesome-css/blob/main/doxygen-awesome.css#L1462). If emojis/symbols don't work for you, you could probably also set a `background-image` or use an icon font. But that will require you to get your hands dirty and overwrite some CSS.

**Comment by Super-Lovers** [comment]
I had the same problem as OP and the error is in this line in the instructions for the **footer.html** changes:
````javascript
document.getElementById("MSearchBox").parentNode.appendChild(toggleButton)
````

The console was throwing an error that it couldn't find MSearchBox or its parent at the time of execution, but copy-pasting this code in the console after it was done loading the page adds the button and it works perfectly. Because of this I moved the location at which it appends the button and changed the css afterwards to make it fit directly from **doxygen-awesome.css** because for some reason I couldn't select the button even if I has a class attached to it. Here is my footer JS:

````javascript
<script type="text/javascript">
  $(document).ready(function(){
      toggleButton = document.createElement('doxygen-awesome-dark-mode-toggle');
      toggleButton.title = "Toggle Light/Dark Mode";
      document.getElementById("main-menu").appendChild(toggleButton);
  })
</script>
````

And my CSS:

````css
doxygen-awesome-dark-mode-toggle {
    float: right;
    margin: 0 var(--spacing-small) 0 var(--spacing-small);
    padding: 0 ;
    width: var(--searchbar-height);
    height: var(--searchbar-height);
    background: none;
    border: none;
    font-size: 23px;
    border-radius: var(--border-radius-medium);
    vertical-align: middle;
    text-align: center;
    line-height: var(--searchbar-height);
}
````

It's just a hotfix CSS though. I hope this works for you OP until there's a fix to the repo here.
