### ISSUE TITLE
Index navigation colors are not overridden in dark mode

### ISSUE THREAD

**Issue by prince-chrismc** [jothepro/doxygen-awesome-css#62]
Firstly this theme is amazing! 😍 

Playing around I noticed these `qindex` elements are styled using the original `.css` so I suspect an override might be missing?

![image](https://user-images.githubusercontent.com/16867443/151649631-dbc2ab7a-0db2-46be-b65d-6354802cd792.png)

## Workaround

I added the following to my `overrides.css`

```css
    html:not(.light-mode) div.qindex,
    html:not(.light-mode) div.navtab {
        background-color: var(--side-nav-background);
        border: 1px solid var(--separator-color);
    }
```

![image](https://user-images.githubusercontent.com/16867443/151649878-9baba871-f335-4125-865a-828c9bb1774d.png)
